version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install aws-sam-cli
  pre_build:
    commands:
      - pip install -r requirements.txt
      - pip install aws-lambda-powertools
      - sam build
  build:
    commands:
      - sam deploy --template-file .aws-sam/build/template.yaml --stack-name lambda-powertools-stack --s3-bucket lambda-powertools-artifacts-2025 --capabilities CAPABILITY_IAM
  post_build:
    commands:
      - echo "Deployment completed on `date`"
artifacts:
  files:
    - .aws-sam/build/template.yaml