version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install aws-sam-cli
  pre_build:
    commands:
      - pip install -r requirements.txt
      - pip install aws-lambda-powertools
      - sam build
  build:
    commands:
      - sam package --s3-bucket lambda-powertools-artifacts-2025 --output-template-file packaged.yaml
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - packaged.yaml